### ISSUE TITLE
Wrong result is generated when running "getEarnings()" function

### ISSUE THREAD

**Issue by johnhan1987** [gsee/qmao#1]
The format of the output is not right.
No numeric values are included.
Could anyone share some thoughts?

Below is the output I got.
![capture](https://f.cloud.github.com/assets/4296190/475576/ffae80b8-b795-11e2-98c3-8a95d957b6bb.png)

**Comment by gsee** [comment]
Please update qmao and XML.  I think I patched this a week or two ago.  The
XML package appears to have changed; readHTMLTable() used to return a
data.frame where the first row was the headers, so getEarnings() and other
functions worked around that by setting the names() to be the first row,
then removing that row.  In the current release of XML, readHTMLTable()
gets the names() right, so my previous work-around is no longer necessary.

Garrett

**Comment by johnhan1987** [comment]
Hi Garrett,

Thanks a lot for your quick response!
Here is my R code. Unfortunately, it still show me the same error, after I
resintall the packages.

install.packages("XML")
install.packages("qmao", repos="http://R-Forge.R-project.org")

library("quantmod")
library("fImport")
library("gdata");library("XML");library("pander");library("RCurl");
library("RJSONIO");library("shiny")
library("qmao")

help(package=qmao)
help(package=quantmod)
ticker <- 'GOOG'
prices <- yahooSeries(symbols = ticker, nDaysBack = 100000)
earnings <- getEarnings(ticker, doFormatTime = TRUE, return.class =
"data.frame")

Best,
John

On Wed, May 8, 2013 at 7:14 AM, Garrett See notifications@github.comwrote:

> Please update qmao and XML. I think I patched this a week or two ago. The
> XML package appears to have changed; readHTMLTable() used to return a
> data.frame where the first row was the headers, so getEarnings() and other
> functions worked around that by setting the names() to be the first row,
> then removing that row. In the current release of XML, readHTMLTable()
> gets the names() right, so my previous work-around is no longer necessary.
> 
> Garrett
> 
> On Tue, May 7, 2013 at 11:12 PM, johnhan1987 notifications@github.comwrote:
> 
> > The format of the output is not right.
> > No numeric values are included.
> > Could anyone share some thoughts?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/gsee/qmao/issues/1>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gsee/qmao/issues/1#issuecomment-17599079
> .

## 

Sincerely,
John Han

**Comment by gsee** [comment]
Please provide your sessionInfo()

$ R --vanilla -q

> suppressPackageStartupMessages(library(qmao))
> head(getEarnings("GOOG", doFormatTime=TRUE, return.class="data.frame"))
>   SYMBOL  PERIOD                     EVENT.TITLE EPS.ESTIMATE EPS.ACTUAL
> 1  GOOG  Q2 2013 Q2 2013 Google Earnings Release        10.83         NA
> 2  GOOG  Q1 2013 Q1 2013 Google Earnings Release        10.66      11.58
> 3  GOOG  Q4 2012 Q4 2012 Google Earnings Release        10.42      10.59
> 4  GOOG  Q3 2012 Q3 2012 Google Earnings Release        10.65       9.03
> 5  GOOG  Q2 2012 Q2 2012 Google Earnings Release        10.04      10.12
> 6  GOOG  Q1 2012 Q1 2012 Google Earnings Release         9.65      10.08
>   PREV.YEAR.ACTUAL                    TIME
> 1            10.12 2013-07-15 15:15:00 CDT
> 2            10.08 2013-04-18 15:15:00 CDT
> 3             9.50 2013-01-22 15:15:00 CST
> 4             9.72 2012-10-18 15:15:00 CDT
> 5             8.74 2012-07-19 15:15:00 CDT
> 6             8.08 2012-04-12 15:15:00 CDT
> Warning message:
> In FUN(c("15-Jul-13 - 19-Jul-13", "18-Apr-13 AMC", "22-Jan-13 AMC",  :
>   Using 1st date of earnings date range
> sessionInfo()
> R version 3.0.0 (2013-04-03)
> Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=C                 LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] qmao_1.6.4                XML_3.96-1.1
[3] gdata_2.12.0.2            FinancialInstrument_1.1.7
[5] quantmod_0.4-0            TTR_0.22-0.1
[7] Defaults_1.1-1            xts_0.9-3.2
[9] zoo_1.7-10

loaded via a namespace (and not attached):
 [1] bitops_1.0-5    caTools_1.14    digest_0.6.3    grid_3.0.0
 [5] gtools_2.7.1    httpuv_1.0.5    lattice_0.20-15 pander_0.3.5
 [9] RCurl_1.95-4.1  RJSONIO_1.0-3   shiny_0.5.0.99  tools_3.0.0
[13] xtable_1.7-1

> system("svn info")
> Path: .
> URL: svn+ssh://gsee@svn.r-forge.r-project.org/svnroot/twsinstrument/pkg
> Repository Root: svn+ssh://
> gsee@svn.r-forge.r-project.org/svnroot/twsinstrument
> Repository UUID: edb9625f-4e0d-4859-8d74-9fd3b1da38cb
> Revision: 415
> Node Kind: directory
> Schedule: normal
> Last Changed Author: gsee
> Last Changed Rev: 415
> Last Changed Date: 2013-05-07 16:03:44 -0500 (Tue, 07 May 2013)

**Comment by johnhan1987** [comment]
> sessionInfo() 
> R version 2.15.3 (2013-03-01)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C  
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] qmao_1.6                FinancialInstrument_1.1 shiny_0.5.0  
 [4] RJSONIO_1.0-3           RCurl_1.95-4.1          bitops_1.0-5  
 [7] pander_0.3.1            XML_3.96-1.1            gdata_2.12.0.2  
[10] fImport_3000.82         timeSeries_3010.97      timeDate_2160.97  
[13] quantmod_0.4-0          TTR_0.22-0              xts_0.9-3.2  
[16] zoo_1.7-9               Defaults_1.1-1         

loaded via a namespace (and not attached):
[1] caTools_1.14    digest_0.6.3    grid_2.15.3     gtools_2.7.1    httpuv_1.0.5  
[6] lattice_0.20-13 Rcpp_0.10.3     tools_2.15.3    xtable_1.7-1

**Comment by johnhan1987** [comment]
Maybe it is because of the R version?
Let me try with 3.0.0

**Comment by johnhan1987** [comment]
Still have the same issue, when I switch to R3.0.0. Do you think the R version would be an issue?
When I try to install "qmao" under R3.0.0. It tells me the qmao is not available under the newest R version.

**Comment by gsee** [comment]
Your sessionInfo() shows that you have qmao_1.6, but you need qmao_1.6.3 or
later.  You can build from source, or wait for R-Forge to build it for you
(it says it's "building", but sometimes it takes a while).

Alternatively, you can click the "Zip" button on github to download the
source (here's the direct link:
https://github.com/gsee/qmao/archive/master.zip).  If you extract the
contents into a folder called "qmao" in your working directory, you should
be able to install.packages("qmao", repos=NULL, type="source")

**Comment by johnhan1987** [comment]
I installed the qmao from the source code. Here is my session info.
![session](https://f.cloud.github.com/assets/4296190/478095/660f9918-b7f1-11e2-8a5a-61033da97910.png)

However, the result still has problems. Here is the output I got.
![capture](https://f.cloud.github.com/assets/4296190/478097/69701790-b7f1-11e2-856c-f2cbf397e005.png)
The colnames are right this time, but the values are not.

**Comment by gsee** [comment]
Thank you for your patience.  I see the problem on Windows; I'll patch.

**Comment by johnhan1987** [comment]
Not a problem! It is a really awesome function and thanks for your contribution.
 Hope this problem won't take you much time. Please let me know when you get it work. 

Thanks you so much!

John

**Comment by gsee** [comment]
patched in Rev. 416.  Please test and let me know if there are any issues.

Thanks for the report!

**Comment by johnhan1987** [comment]
Just tested. It works well. Below is the output.
![capture](https://f.cloud.github.com/assets/4296190/478688/22e7deb0-b801-11e2-9700-799dd72eef30.png)

I think there exists an small issue. In line 8-10, the strings got duplicated.
BTW, is there any potential problems in the "warning messages"?

**Comment by gsee** [comment]
Doh! I just realized that my change removed the decimals in the earnings
numbers.  I'll fix and report back.

I do not see what you mean by "the strings got duplicated."  For
comparison, here is the page that is being scraped:
http://www.earnings.com/company.asp?client=cb&ticker=goog

Of course the "PREV.YEAR.ACTUAL" is the same "EPS.ACTUAL" 4 quarters later.
 Is that what's confusing, or am I missing something?

The warning message is telling you that earnings.com gave a value like
15-Jul-13
- 19-Jul-13" for the "DATE/TIME."  (you can see this if you use
  doFormatTime=FALSE).  Since you called getEarnings with doFormatTime=TRUE,
  it has to convert that date range into a single time.  So, it picks the
  first time as "THE" earnings time even though the actual date may be later
  in the week.

**Comment by johnhan1987** [comment]
Great!
I was pointing to the "EVENT.TITLE" column. It has different format in line 8-10.
Now I understand, basically, you are using this column to extract the quarter and year value. So I could just ignore this column?

**Comment by gsee** [comment]
earnings.com has a "PERIOD" column and an "EVENT TYPE" column.  I'm
basically just returning the stuff in the "Earnings Releases" section of
this page (about halfway down the page)
http://www.earnings.com/company.asp?client=cb&ticker=GOOG)

earnings.com is not terribly consistent with how they format things.

You are correct that the EVENT TYPE column contains some redundant
information that is also included in the PERIOD column.  You're free to
ignore whatever you want. ;-).  Personally, I always call this function
with the defaults (return.class="xts") which means that I ignore both the
PERIOD and EVENT.TYPE columns.  But, it depends on why/how you are using
the data.

I fixed the missing decimal issue in Rev. 417 (packageVersion 1.6.5.1).

**Comment by johnhan1987** [comment]
It is perfect! Thanks, Garrett.

FYI, I just realized that "www.earnings.com" seems updated quite slow when the new earnings report is published.
Check this out! The actual earning for first quarter can be found at other website.
![capture](https://f.cloud.github.com/assets/4296190/478957/38d20460-b808-11e2-8c51-3226361c53b0.png)

**Comment by gsee** [comment]
Yes, but is there another website that tells you that the next earnings
report will be during the week of 2013-08-05?  The real value that I get
from earnings.com is that it tells me the dates of future earnings well in
advance.  I'm less concerned with what the actually earnings numbers are,
but I understand why those numbers might matter to other people ;-)

**Comment by johnhan1987** [comment]
Gocha:~)

**Comment by gsee** [comment]
The patch I applied only keeps characters that I want to keep as opposed to trying to remove characters I do not want.  Unfortunately, I forgot to keep colons (:) which means that times were not parsed correctly when doFormatTime=TRUE.  You can see from your output above that one of the times is `<NA>`, but it should be 2011-04-25 07:30:00 CDT (assuming return.tz="America/Chicago").  So, I added colons and some other punctuation to the list of characters to not be removed in Rev. 418 (packageVersion 1.6.5.2)

**Comment by johnhan1987** [comment]
I was thinking it might be caused by missing values.
Just tried the newest version and it works well. No more "NA" is printed in the Date column!
Thanks.
